[package]
name = "maxops-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
color-eyre.workspace = true
axum.workspace = true
reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
subtle.workspace = true
tokio.workspace = true

jiff.workspace = true
utoipa.workspace = true

[dev-dependencies]
jsonschema = { version = "0.56", default-features = false }
criterion.workspace = true

[[bench]]
name = "protocol"
harness = false
