[package]
name = "maxops-executor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
blake3.workspace = true
clap.workspace = true
color-eyre.workspace = true
futures.workspace = true
jiff.workspace = true
maxops-proto.workspace = true
maxops-store.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
zbus.workspace = true

[dev-dependencies]
tempfile = "3"
