self:
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.services.maxops-hub;
  credentialDir = "/run/credentials/maxops-hub.service";
  hosts = lib.imap0 (i: host: {
    name = host.name;
    site = host.site;
    agent_url = host.agentUrl;
    agent_token_file = "${credentialDir}/agent-${toString i}";
    execution_token_file =
      if host.executionTokenFile == null then null else "${credentialDir}/execution-${toString i}";
    readable_units = host.readableUnits;
  }) cfg.hosts;
  clients = lib.imap0 (i: client: {
    name = client.name;
    token_file = "${credentialDir}/client-${toString i}";
    inherit (client) hosts capabilities access;
  }) cfg.clients;
  secretFiles =
    map (host: host.tokenFile) cfg.hosts
    ++ lib.filter (path: path != null) (map (host: host.executionTokenFile) cfg.hosts)
    ++ map (client: client.tokenFile) cfg.clients
    ++ lib.optional cfg.alertIngress.enable cfg.alertIngress.tokenFile
    ++ lib.optional (
      cfg.alertIngress.enable && cfg.alertIngress.sinkTokenFile != null
    ) cfg.alertIngress.sinkTokenFile;
  configFile = (pkgs.formats.json { }).generate "maxops-hub.json" {
    listen = "${cfg.listenAddress}:${toString cfg.port}";
    state_file = "/var/lib/maxops-hub/state.db";
    inherit hosts clients;
    prometheus_url = cfg.prometheusUrl;
    alertmanager_url = cfg.alertmanagerUrl;
    alert_ingress =
      if cfg.alertIngress.enable then
        {
          token_file = "${credentialDir}/alert-ingress";
          sink_url = cfg.alertIngress.sinkUrl;
          sink_token_file =
            if cfg.alertIngress.sinkTokenFile == null then null else "${credentialDir}/alert-sink";
        }
      else
        null;
  };
in
{
  options.services.maxops-hub = {
    enable = lib.mkEnableOption "the maxops fleet hub";
    package = lib.mkOption {
      type = lib.types.package;
      default = self.packages.${pkgs.stdenv.hostPlatform.system}.default;
      description = "Package containing maxops-hub.";
    };
    listenAddress = lib.mkOption {
      type = lib.types.str;
      default = "127.0.0.1";
      description = "Explicit bind address; bracket IPv6 literals.";
    };
    port = lib.mkOption {
      type = lib.types.port;
      default = 9721;
      description = "Hub HTTP port.";
    };
    prometheusUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Optional Prometheus base URL for exporter observations.";
    };
    alertmanagerUrl = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Optional Alertmanager base URL for active alerts.";
    };
    hosts = lib.mkOption {
      default = [ ];
      description = "Inventory generated by the consuming Nix configuration.";
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            name = lib.mkOption {
              type = lib.types.str;
              description = "Inventory name.";
            };
            site = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = "Informational failure-domain label.";
            };
            agentUrl = lib.mkOption {
              type = lib.types.str;
              description = "Agent base URL.";
            };
            tokenFile = lib.mkOption {
              type = lib.types.str;
              description = "Runtime agent credential path.";
            };
            executionTokenFile = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = "Optional dedicated credential for the agent management endpoint.";
            };
            readableUnits = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
              description = "Exact readable service names, also configured on the agent.";
            };
          };
        }
      );
    };
    clients = lib.mkOption {
      default = [ ];
      description = "Authenticated principals with explicit host and capability grants.";
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            name = lib.mkOption {
              type = lib.types.str;
              description = "Audit identity, never supplied by request parameters.";
            };
            tokenFile = lib.mkOption {
              type = lib.types.str;
              description = "Runtime client credential path.";
            };
            hosts = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
              description = "Exact permitted inventory names; no wildcard.";
            };
            capabilities = lib.mkOption {
              type = lib.types.listOf (
                lib.types.enum [
                  "fleet:read"
                  "host:read"
                  "metrics:read"
                  "units:read"
                  "logs:read"
                  "alerts:read"
                  "exec:run"
                  "jobs:read"
                  "jobs:cancel"
                ]
              );
              default = [ ];
              description = "Explicit operation capabilities.";
            };
            access = lib.mkOption {
              type = lib.types.enum [
                "observe"
                "manage"
              ];
              default = "observe";
              description = "Credential class; manage is required for every job operation.";
            };
          };
        }
      );
    };
    alertIngress = {
      enable = lib.mkEnableOption "authenticated synchronous Alertmanager webhook forwarding";
      tokenFile = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "Dedicated runtime ingress credential path.";
      };
      sinkUrl = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "Webhook receiving the Alertmanager v4 payload.";
      };
      sinkTokenFile = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Optional runtime sink credential path.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.clients != [ ];
        message = "maxops-hub requires at least one authenticated client.";
      }
      {
        assertion =
          !(builtins.elem cfg.listenAddress [
            "0.0.0.0"
            "::"
            "[::]"
          ]);
        message = "maxops-hub requires an explicit bind address.";
      }
      {
        assertion = lib.all (
          path: lib.hasPrefix "/" path && !(lib.hasPrefix builtins.storeDir path)
        ) secretFiles;
        message = "maxops-hub tokens must use runtime paths outside the Nix store.";
      }
    ];
    systemd.services.maxops-hub = {
      description = "maxops read-only fleet hub";
      wantedBy = [ "multi-user.target" ];
      after = [
        "network-online.target"
        "tailscaled.service"
      ];
      wants = [ "network-online.target" ];
      environment.RUST_LOG = "info";
      serviceConfig = {
        ExecStart = "${cfg.package}/bin/maxops-hub --config ${configFile}";
        DynamicUser = true;
        LoadCredential =
          (lib.imap0 (i: host: "agent-${toString i}:${host.tokenFile}") cfg.hosts)
          ++ (lib.concatLists (
            lib.imap0 (
              i: host:
              lib.optional (
                host.executionTokenFile != null
              ) "execution-${toString i}:${host.executionTokenFile}"
            ) cfg.hosts
          ))
          ++ (lib.imap0 (i: client: "client-${toString i}:${client.tokenFile}") cfg.clients)
          ++ lib.optional cfg.alertIngress.enable "alert-ingress:${cfg.alertIngress.tokenFile}"
          ++ lib.optional (
            cfg.alertIngress.enable && cfg.alertIngress.sinkTokenFile != null
          ) "alert-sink:${cfg.alertIngress.sinkTokenFile}";
        Restart = "on-failure";
        RestartSec = "10s";
        TimeoutStopSec = "15s";
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        PrivateDevices = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
        RestrictSUIDSGID = true;
        RestrictAddressFamilies = [
          "AF_UNIX"
          "AF_INET"
          "AF_INET6"
        ];
        CapabilityBoundingSet = "";
        LockPersonality = true;
        UMask = "0077";
        StateDirectory = "maxops-hub";
        StateDirectoryMode = "0700";
      };
    };
  };
}
